name: Continuous Integration with Github Actions

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login - Azure Contrainer Registry
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
        
    - name: Build Images
      working-directory: ./03_RestWithASPNETUdemy_Calculator_Post/RestWithASPNETUdemy
      run: docker-compose build
      
    - name: Push to Azure Container registry
      run: |
          docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
          
    - name: Login in Azure to Deployment
      uses: Azure/login@v1.4.4
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure WebApp Container - Application Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.DOCKER_SERVER }}
        images:  ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
